package co.yore.splitnpay.models

object DataIds {
    const val statusBarColor = -1
    const val textInput = 0
    const val groupsAndPeoples = 1
    const val checkItem = 2
    const val addedContacts = 3
    const val deleteAdded = 4
    const val selectedTabIndex = 5
    const val groups = 6
    const val contacts = 7
    const val selecteds = 8
    const val proceedWithContacts = 9

    const val whole = 10
    const val decimal = 11
    const val wholeGet = 12
    const val decimalGet = 13
    const val wholePay= 14
    const val decimalPay = 15
    const val ultimateState = 16
    const val peoples = 17
    const val willGetActive = 18
    const val willPayActive = 19
    const val subTab = 20
    const val noGroup = 21
    const val back = 22
    const val getCard = 23
    const val payCard = 24
    const val groupCardGo = 25
    const val peopleCardGo = 26
    const val addGroup = 27
    const val split = 28
    const val peopleCard = 29
    const val groupCard = 30
    const val haveSplit = 31
    const val checkGroupItem = 32
    const val groupsChecked = 33
    const val pickImage = 34
    const val groupName = 35
    const val cameraOrGallery = 36
    const val profileImage = 37
    const val transactions = 38
    const val groupAmount = 39
    const val groupImage = 40
    const val groupCreationDate = 41
    const val isSingleChat = 42
    const val filteredMemberName = 43
    const val filteredMemberImage = 44
    const val settleClick = 45
    const val summaryClick = 46
    const val manageClick = 47
    const val cardClick = 48
    const val searchText = 49
    const val chatMessage = 50
    const val proceed = 51
    const val filter = 52
    const val conversations = 53
    const val membersForFiltering = 54
    const val filterMember = 55
    const val filterDone = 56
}